[versions]
isPreview = "false" # true

# https://developer.android.com/studio/releases/build-tools.html#notes
buildTools = "37.0.0"
buildToolsPreview = "37.0.0"

minSdk = "23"

compileSdk = "37"
compileSdkMinor = "2"
compileSdkPreview = "37.2-beta3"
# compileSdkPreview = "CinnamonBun"
# compileSdkPreview = "CANARY"

compileSdkExtension = "24" # 37.2-ext24

targetSdk = "37"
targetSdkPreview = "DEV"
# targetSdkPreview = "CinnamonBun"
# targetSdkPreview = "CANARY"

# https://github.com/android/ndk/releases
ndk = "30.0.16138531"
# https://cmake.org/cmake/help/latest/release/index.html
cmake = "4.1.2"

versionCode = "73"
versionName = "1.18.8_unpublished"

javaToolchain = "25"