[versions]
isPreview = "false" # true

# https://developer.android.com/studio/releases/build-tools.html#notes
buildTools = "37.0.0"
buildToolsPreview = "37.0.0"

minSdk = "23"

compileSdk = "37"
compileSdkMinor = "0"
compileSdkPreview = "CinnamonBun"
# compileSdkPreview = "CANARY"

compileSdkExtension = "22" # 37.0-ext22

targetSdk = "37"
targetSdkPreview = "CinnamonBun"
# targetSdkPreview = "CANARY"

# https://github.com/android/ndk/releases
ndk = "30.0.14904198"
# https://cmake.org/cmake/help/latest/release/index.html
cmake = "4.1.2"

versionCode = "73"
versionName = "1.18.8_unpublished"

javaToolchain = "25"