name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # https://github.com/actions/checkout
    - uses: actions/checkout@v5

    # region [JDK]
    # https://github.com/actions/setup-java
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    # endregion [JDK]

    # region [Android SDK]
    # https://github.com/android-actions/setup-android
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: ''
    # https://developer.android.com/tools/sdkmanager#install
    # https://github.com/imknown/AndroidLowLevelDetector/blob/develop/gradle/toml/build.toml
    - name: Install Android SDK Cmake
      run: sdkmanager --install "cmake;4.1.1"
    - name: Install Android SDK NDK
      # https://github.com/android/ndk/releases
      run: sdkmanager --install "ndk;29.0.14206865"
    # endregion [Android SDK]

    # region [Gradle]
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleFossDebug
    # endregion [Gradle]