name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    # https://github.com/android-actions/setup-android
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: ''
    # https://developer.android.com/tools/sdkmanager#install
    - name: Install Android SDK Cmake
      run: sdkmanager --install "cmake;4.0.2"
    - name: Install Android SDK NDK
      run: sdkmanager --install "ndk;29.0.13113456 rc1"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleFossDebug
