name: Dependency Submission

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: write

jobs:
  # https://github.com/gradle/actions/blob/main/docs/dependency-submission.md
  # https://github.com/actions/gradle-build-tools-actions/blob/main/docs/dependency-submission.md
  dependency-submission:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      # region [Android SDK]
      # https://github.com/android-actions/setup-android
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: ''
      # https://developer.android.com/tools/sdkmanager#install
      # https://github.com/imknown/AndroidLowLevelDetector/blob/develop/gradle/toml/build.toml
      - name: Install Android SDK Cmake
        run: sdkmanager --install "cmake;4.0.2"
      - name: Install Android SDK NDK
        # https://github.com/android/ndk/releases
        run: sdkmanager --install "ndk;29.0.13113456"
      # endregion [Android SDK]

      - name: Run dependency submission
        uses: gradle/actions/dependency-submission@v4
        with:
          gradle-project-path: "."
          gradle-build-module: ":app"